// <auto-generated />
using FoodOrderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260707110006_SeedFoodCategoryData")]
    partial class SeedFoodCategoryData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodOrderAPI.Models.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Pizza",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Burger",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Biryani",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Drinks",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Desserts",
                            IsActive = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
